#!/usr/bin/env bash
#
# Regenerates internal/gce/machinetypes_gen.go from the Compute Engine API.
#
# The vCPU and memory figures for predefined machine types are pulled from the
# API rather than derived from the machine type name, because the names are not
# a reliable grammar: the trailing number in "g2-standard-8" is a vCPU count,
# while the trailing number in "a2-highgpu-1g" is a GPU count. The generated
# table is committed so that the provider needs no credentials at runtime and
# so that any change to the data shows up in review as a diff.
#
# Usage:
#   GCE_METADATA_GEN_PROJECT=my-project tools/generate-machine-types.sh

set -euo pipefail

if [[ -z "${GCE_METADATA_GEN_PROJECT:-}" ]]; then
  cat >&2 <<'EOF'
error: GCE_METADATA_GEN_PROJECT is not set

Set it to any GCP project you can read machine types from. The choice of
project does not affect the output: machine type definitions are global, so
any project reachable with your credentials produces the same table.

  GCE_METADATA_GEN_PROJECT=my-project tools/generate-machine-types.sh
EOF
  exit 1
fi

readonly PROJECT="${GCE_METADATA_GEN_PROJECT}"

# Machine series modeled by this provider: general-purpose and compute-optimized.
# Accelerator-optimized, memory-optimized, and storage-optimized series are out
# of scope. Keep this in sync with the series table in internal/gce/series.go.
readonly SERIES_FILTER='^(c2|c2d|c3|c3d|c4|c4a|c4d|e2|h3|n1|n2|n2d|n4|n4a|n4d|t2a|t2d)-'

readonly REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly OUT="${REPO_ROOT}/internal/gce/machinetypes_gen.go"

for cmd in gcloud jq gofmt; do
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "error: ${cmd} is required but not installed" >&2
    exit 1
  fi
done

echo "Fetching machine types from project ${PROJECT}..." >&2

rows="$(
  gcloud compute machine-types list \
    --project "${PROJECT}" \
    --filter="name~'${SERIES_FILTER}'" \
    --format="json(name,guestCpus,memoryMb,isSharedCpu)" |
    jq -r '
      # A machine type is defined per zone, so the same name comes back once per
      # zone. unique_by collapses that into the union across all zones.
      unique_by(.name)

      # Natural order: a lexical sort puts n2-standard-16 ahead of
      # n2-standard-2, so compare each hyphen-separated segment numerically
      # where it is a number and as text otherwise.
      | sort_by(.name | split("-") | map(if test("^[0-9]+$") then tonumber else . end))

      | .[]
      | [.name, (.guestCpus | tostring), (.memoryMb | tostring), (.isSharedCpu | tostring)]
      | @tsv
    '
)"

if [[ -z "${rows}" ]]; then
  echo "error: no machine types returned; check credentials and project ${PROJECT}" >&2
  exit 1
fi

count="$(wc -l <<<"${rows}" | tr -d ' ')"
echo "Writing ${count} machine types to ${OUT}" >&2

{
  cat <<'EOF'
// Copyright (c) Persona
// SPDX-License-Identifier: MPL-2.0

// Code generated by tools/generate-machine-types.sh; DO NOT EDIT.

package gce

// machineTypes is every predefined machine type in the modeled series, keyed by
// machine type name. Custom machine types are an unbounded name space and are
// therefore not present here; Lookup resolves those separately.
var machineTypes = map[string]MachineType{
EOF

  # Series is the name segment before the first hyphen, and shape the segment
  # after it. Both are recorded literally in the generated output so that a
  # mis-split is visible in review rather than hidden behind runtime logic.
  awk -F'\t' '{
    split($1, parts, "-")
    shared = ($4 == "true") ? ", SharedCore: true" : ""
    printf "\t\"%s\": {MemoryMB: %s, Name: \"%s\", Series: \"%s\", Shape: \"%s\"%s, VCPUs: %s},\n", \
      $1, $3, $1, parts[1], parts[2], shared, $2
  }' <<<"${rows}"

  echo "}"
} >"${OUT}"

gofmt -s -w "${OUT}"

echo "Done." >&2
